const constants = {
	SET_READERS: 'SET_READERS',
    CLEAR_READERS: 'CLEAR_READERS',

    SET_ACCESS_LEVELS: 'SET_ACCESS_LEVELS',
    CLEAR_ACCESS_LEVELS: 'CLEAR_ACCESS_LEVELS',

    SET_READER_TYPES: 'SET_READER_TYPES',
    CLEAR_READER_TYPES: 'CLEAR_READER_TYPES',

    SET_READER_SEARCH_FILTER: 'SET_READER_SEARCH_FILTER',
    CLEAR_READER_SEARCH_FILTER: 'CLEAR_READER_SEARCH_FILTER',

    SET_SELECTED_READER: 'SET_SELECTED_READER',
    CLEAR_SELECTED_READER: 'CLEAR_SELECTED_READER',

};

export default constants;
